#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TOP_DIR="$(cd "$DIR/../" && pwd)"

#/ Usage:
#/ Description:
#/ Examples:
#/ Options:
#/   --help: Display this help message
usage() { grep '^#/' "$0" | cut -c4- ; exit 0 ; }
expr "$*" : ".*--help" > /dev/null && usage

readonly LOG_FILE="/tmp/$(basename "$0").log"
info()    { echo "[INFO]    $@" | tee -a "$LOG_FILE" >&2 ; }
warning() { echo "[WARNING] $@" | tee -a "$LOG_FILE" >&2 ; }
error()   { echo "[ERROR]   $@" | tee -a "$LOG_FILE" >&2 ; }
fatal()   { echo "[FATAL]   $@" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }

cleanup() {
  echo ""
  info "Exiting. Bringing docker down..."
  cd "${TOP_DIR}/support" && docker-compose -f "$DIR/docker-compose.yml" down
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
  trap cleanup EXIT

  info "Starting."
  if ! docker volume inspect kutt-nodemodules_root &>/dev/null || \
     ! docker volume inspect kutt-nodemodules_backend &>/dev/null || \
     ! docker volume inspect kutt-nodemodules_frontend &>/dev/null; then
    info "Installing dependencies..."

    docker volume create --name=kutt-nodemodules_root
    docker volume create --name=kutt-nodemodules_backend
    docker volume create --name=kutt-nodemodules_frontend

    docker-compose -f "$DIR/docker-compose.builder.yml" run --rm install
  fi;

  info "Bringing docker up..."
  cd "${TOP_DIR}/support" && docker-compose -f "$DIR/docker-compose.yml" up
fi
