version: "3"

services:
  redis:
    image: redis:alpine
    container_name: kutt-redis
    ports:
      - "63790:6379"
    networks:
      - kutt-network

  postgres:
    image: postgres:12-alpine
    container_name: kutt-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kutt
    ports:
      - "54323:5432"
    networks:
      - kutt-network

networks:
  kutt-network:
    driver: "bridge"
