version: "2"

services:
  install:
    image: node:12-alpine
    container_name: kutt-builderbase
    volumes:
      - kutt-nodemodules_root:/usr/src/kutt/node_modules
      - kutt-nodemodules_backend:/usr/src/kutt/apps/backend/node_modules
      - kutt-nodemodules_frontend:/usr/src/kutt/apps/frontend/node_modules
      - ../:/usr/src/kutt:cached
    working_dir: /usr/src/kutt
    command: yarn

volumes:
  kutt-nodemodules_root:
    external: true
  kutt-nodemodules_backend:
    external: true
  kutt-nodemodules_frontend:
    external: true
